CREATE TABLE IF NOT EXISTS definitions (
    id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL DEFAULT 0,
    word TEXT NOT NULL,
    description TEXT NOT NULL,
    author TEXT DEFAULT 'Anonymous'
);
